import{a as l}from"./assets/vendor-0cb09735.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&c(r)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();async function d(t){return await l.get(`https://books-backend.p.goit.global/books/category?category=${t}`)}const i=document.querySelector(".test-button"),u=document.querySelector(".books-list");document.addEventListener("DOMContentLoaded",()=>{localStorage.getItem("isButtonHidden")==="true"&&(i.style.display="none")});i.addEventListener("click",async()=>{try{const t="Hardcover Fiction",n=(await d(t)).data;console.log(n);const c=n.map(({book_image:o,title:r,author:a})=>({book_image:o,title:r,author:a})),e=p(t,c);u.innerHTML=e,localStorage.setItem("isButtonHidden","true"),i.style.display="none"}catch(t){console.error(t)}});function p(t,s){const n=`<h2 class="hardcover-category-title">${t.replace(/(\w+)/g,(e,o,r)=>r===0?e:`<span class="book-categories-span">${e}</span>`)}</h2>`,c=s.map(({book_image:e,title:o,author:r})=>`<li class="hardcover-item">         
            <div class="hardcover-container">
                <div class="hardcover-wrapper">
                    <img class="hardcover-image" src="${e}"/>
                    <div class="hardcover-text-container">
                        <h2 class="hardcover-title">${o}</h2>
                        <p class="hardcover-text">${r}</p>
                    </div>
                </div>
            </div>
        </li>`).join("");return n+'<ul class="hardcover-list">'+c+"</ul>"}const g=document.querySelector(".modal-close-btn");document.querySelector(".backdrop");function y(){const t=document.querySelector(".backdrop");t.style.display="none"}g.addEventListener("click",()=>{y()});function f(){const t=document.querySelector(".shopping-list");t.textContent==="Add to shopping list"?t.textContent="Remove from the shopping list":t.textContent="Add to shopping list"}document.querySelector(".shopping-list").addEventListener("click",f);
//# sourceMappingURL=commonHelpers.js.map
