import{S as m,a as p}from"./assets/vendor-d5a47558.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();document.addEventListener("DOMContentLoaded",function(){var e=document.querySelector(".switch input");e.addEventListener("change",function(){e.checked?document.body.classList.add("dark-mode"):document.body.classList.remove("dark-mode")})});var u=document.querySelectorAll(".nav-link");u.forEach(function(e){e.addEventListener("click",function(){u.forEach(function(r){r.classList.remove("is-active")}),e.classList.add("is-active")})});new m(".swiper-container",{slidesPerView:6,spaceBetween:20,direction:"vertical",speed:400,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});async function y(e){return await p.get(`https://books-backend.p.goit.global/books/category?category=${e}`)}async function f(e){return await p.get(`https://books-backend.p.goit.global/books/${e}`)}const h=document.querySelector(".js-list"),k=document.querySelectorAll(".js-category"),v=document.querySelector(".books-list");h.addEventListener("click",async e=>{try{if(Array.from(k).includes(e.target)){const r=e.target.textContent.trim(),c=(await y(r)).data;console.log(c);const t=c.map(({_id:s,book_image:i,title:a,author:l})=>({book_image:i,title:a,author:l,_id:s})),o=b(r,t);v.innerHTML=o,localStorage.setItem("isButtonHidden","true")}}catch(r){console.error(r)}});function b(e,r){const n=`<h2 class="hardcover-category-title">${e.replace(/(\w+)/g,(t,o,s)=>s===0?t:`<span class="book-categories-span">${t}</span>`)}</h2>`,c=r.map(({_id:t,book_image:o,title:s,author:i})=>`<li class="hardcover-item" id=${t}>         
            <div class="hardcover-container">
                <div class="hardcover-wrapper">
                    <img class="hardcover-image" src="${o}"/>
                    <div class="hardcover-text-container">
                        <h2 class="hardcover-title">${s}</h2>
                        <p class="hardcover-text">${i}</p>
                    </div>
                </div>
            </div>
        </li>`).join("");return n+'<ul class="hardcover-list">'+c+"</ul>"}f("643282b1e85766588626a0dc").then(e=>{const r=e.data,{_id:n,book_image:c,title:t,list_name:o,description:s,author:i,buy_links:a}=r,l=a.slice(0,2),d={id:n,book_image:c,title:t,list_name:o,description:s,author:i,selectedLinks:l};localStorage.setItem("bookData",JSON.stringify(d));function g(){(JSON.parse(localStorage.getItem("bookData"))||{}).id===d.id&&localStorage.removeItem("bookData")}g()}).catch(e=>{console.log("Error:",e)});const S=document.querySelector(".js-btn"),L=document.querySelector(".empty-list-text"),B=document.querySelector(".shopping-list-js");console.log(B);S.addEventListener("click",w);function w(e){e.preventDefault(),localStorage.length||(L.textContent="This page is empty, add some books and proceed to order.")}const q=document.querySelector(".modal-close-btn");document.querySelector(".backdrop");function E(){const e=document.querySelector(".backdrop");e.style.display="none"}q.addEventListener("click",()=>{E()});function x(){const e=document.querySelector(".shopping-list");e.textContent==="Add to shopping list"?e.textContent="Remove from the shopping list":e.textContent="Add to shopping list"}document.querySelector(".shopping-list").addEventListener("click",x);
//# sourceMappingURL=commonHelpers.js.map
