import{S as l,a as u}from"./assets/vendor-d5a47558.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();document.addEventListener("DOMContentLoaded",function(){var e=document.querySelector(".switch input");e.addEventListener("change",function(){e.checked?document.body.classList.add("dark-mode"):document.body.classList.remove("dark-mode")})});var a=document.querySelectorAll(".nav-link");a.forEach(function(e){e.addEventListener("click",function(){a.forEach(function(r){r.classList.remove("is-active")}),e.classList.add("is-active")})});new l(".swiper-container",{slidesPerView:6,spaceBetween:20,direction:"vertical",speed:400,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});async function p(e){return await u.get(`https://books-backend.p.goit.global/books/category?category=${e}`)}const i=document.querySelector(".test-button"),g=document.querySelector(".books-list");document.addEventListener("DOMContentLoaded",()=>{localStorage.getItem("isButtonHidden")==="true"&&(i.style.display="none")});i.addEventListener("click",async()=>{try{const e="Hardcover Fiction",s=(await p(e)).data;console.log(s);const c=s.map(({book_image:o,title:n,author:d})=>({book_image:o,title:n,author:d})),t=m(e,c);g.innerHTML=t,localStorage.setItem("isButtonHidden","true"),i.style.display="none"}catch(e){console.error(e)}});function m(e,r){const s=`<h2 class="hardcover-category-title">${e.replace(/(\w+)/g,(t,o,n)=>n===0?t:`<span class="book-categories-span">${t}</span>`)}</h2>`,c=r.map(({book_image:t,title:o,author:n})=>`<li class="hardcover-item">         
            <div class="hardcover-container">
                <div class="hardcover-wrapper">
                    <img class="hardcover-image" src="${t}"/>
                    <div class="hardcover-text-container">
                        <h2 class="hardcover-title">${o}</h2>
                        <p class="hardcover-text">${n}</p>
                    </div>
                </div>
            </div>
        </li>`).join("");return s+'<ul class="hardcover-list">'+c+"</ul>"}const y=document.querySelector(".modal-close-btn");document.querySelector(".backdrop");function f(){const e=document.querySelector(".backdrop");e.style.display="none"}y.addEventListener("click",()=>{f()});function v(){const e=document.querySelector(".shopping-list");e.textContent==="Add to shopping list"?e.textContent="Remove from the shopping list":e.textContent="Add to shopping list"}document.querySelector(".shopping-list").addEventListener("click",v);
//# sourceMappingURL=commonHelpers.js.map
